"""Enable auto-increment for primary key

Revision ID: fa95f3008cda
Revises: 
Create Date: 2023-08-01 13:02:39.357663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa95f3008cda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index('location_name_UNIQUE')
        batch_op.drop_index('product_pid_idx')

    op.drop_table('location')
    with op.batch_alter_table('product_movement', schema=None) as batch_op:
        batch_op.drop_index('from_location_id_idx')
        batch_op.drop_index('product_pid_idx')
        batch_op.drop_index('to_location_id_idx')

    op.drop_table('product_movement')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('product_movement',
    sa.Column('product_movement_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_stamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['location.location_id'], name='from_location_id'),
    sa.ForeignKeyConstraint(['product_product_id'], ['product.product_id'], name='product_product_id'),
    sa.ForeignKeyConstraint(['to_location_id'], ['location.location_id'], name='to_location_id'),
    sa.PrimaryKeyConstraint('product_movement_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product_movement', schema=None) as batch_op:
        batch_op.create_index('to_location_id_idx', ['to_location_id'], unique=False)
        batch_op.create_index('product_pid_idx', ['product_product_id'], unique=False)
        batch_op.create_index('from_location_id_idx', ['from_location_id'], unique=False)

    op.create_table('location',
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_pid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_name', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_pid'], ['product.product_id'], name='product_pid'),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index('product_pid_idx', ['product_pid'], unique=False)
        batch_op.create_index('location_name_UNIQUE', ['location_name'], unique=False)

    # ### end Alembic commands ###
